# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout: true
            anonymous: ~

    access_control:
        - { path: ^/payments, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/search/referrers, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/cabinet, role: ROLE_USER }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_SONATA_ADMIN
            - ROLE_USER
            - ROLE_ADMIN_POOL_LIST
            - ROLE_ADMIN_POOL_VIEW
            - ROLE_ADMIN_RATE_LIST
            - ROLE_ADMIN_RATE_VIEW
            - ROLE_ADMIN_USER_LIST
            - ROLE_ADMIN_USER_VIEW
            - ROLE_ADMIN_ACCOUNT_LIST
            - ROLE_ADMIN_ACCOUNT_VIEW
            - ROLE_ADMIN_MONEY_TRANSACTION_LIST
            - ROLE_ADMIN_MONEY_TRANSACTION_VIEW
            - ROLE_ADMIN_TICKET_LIST
            - ROLE_ADMIN_TICKET_VIEW
            - ROLE_ADMIN_INVOICE_LIST
            - ROLE_ADMIN_INVOICE_VIEW
            - ROLE_ADMIN_ISSUE_LIST
            - ROLE_ADMIN_ISSUE_VIEW
            - ROLE_ADMIN_NEWS_CREATE
            - ROLE_ADMIN_NEWS_EDIT
            - ROLE_ADMIN_NEWS_DELETE
            - ROLE_ADMIN_NEWS_LIST
            - ROLE_ADMIN_NEWS_VIEW
        ROLE_SUPER_ADMIN: ROLE_ADMIN
