perfect_money_success:
    path:     /perfectmoney/success
    defaults: { _controller: PerfectMoneyBundle:Default:success }
    methods:  [POST]

perfect_money_failed:
    path:     /perfectmoney/failed
    defaults: { _controller: PerfectMoneyBundle:Default:failed }
    methods:  [POST]

perfect_money_confirm:
    path:     /perfectmoney/confirm
    defaults: { _controller: PerfectMoneyBundle:Default:confirmation }
    methods:  [POST]
