app_profile:
    path:     /
    defaults: { _controller: AppBundle:Cabinet:profile }

app_cloud:
    path:     /cloud
    defaults: { _controller: AppBundle:Cabinet:cloud }

app_history:
    path:     /history
    defaults: { _controller: AppBundle:Cabinet:history }

app_content:
    path:     /content
    defaults: { _controller: AppBundle:Cabinet:content }

app_news:
    path:     /news
    defaults: { _controller: AppBundle:Cabinet:news }

app_faq:
    path:     /faq
    defaults: { _controller: AppBundle:Cabinet:faq }

app_dashboard:
    path:     /dashboard
    defaults: { _controller: AppBundle:Dashboard:index }

app_dashboard_open:
    path:     /dashboard/open/{rate}
    defaults: { _controller: AppBundle:Dashboard:open }

app_dashboard_prolong:
    path:     /dashboard/prolong/{ticket}
    defaults: { _controller: AppBundle:Dashboard:prolong }

app_payment_success:
    path:     /payment/success
    defaults: { _controller: AppBundle:Payment:success }

app_payment_failed:
    path:     /payment/failed
    defaults: { _controller: AppBundle:Payment:failed }

app_api_accounts:
    path:     /api/accounts
    defaults: { _controller: AppBundle:API:accounts }
    methods:  [POST]

app_api_avatars:
    path:     /api/avatars
    defaults: { _controller: AppBundle:API:postAvatars }
    methods:   [POST]
