app_profile:
    path:     /
    defaults: { _controller: AppBundle:Default:profile }

app_cloud:
    path:     /cloud
    defaults: { _controller: AppBundle:Default:cloud }

app_history:
    path:     /history
    defaults: { _controller: AppBundle:Default:history }

app_news:
    path:     /news
    defaults: { _controller: AppBundle:Default:news }

app_faq:
    path:     /faq
    defaults: { _controller: AppBundle:Default:faq }

app_support:
    path:     /support
    defaults: { _controller: AppBundle:Default:support }

app_dashboard:
    path:     /dashboard
    defaults: { _controller: AppBundle:Dashboard:index }

app_dashboard_open:
    path:     /dashboard/open/{rate}
    defaults: { _controller: AppBundle:Dashboard:open }

app_dashboard_prolong:
    path:     /dashboard/prolong/{ticket}
    defaults: { _controller: AppBundle:Dashboard:prolong }

app_api_accounts:
    path:     /api/accounts
    defaults: { _controller: AppBundle:API:accounts }
    methods:  [POST]

app_api_avatars:
    path:     /api/avatars
    defaults: { _controller: AppBundle:API:postAvatars }
    methods:  [POST]
