landing:
    path:     /
    defaults: { _controller: AppBundle:Landing:index }

index:
    path:     /cabinet
    defaults: { _controller: AppBundle:Cabinet:index }

profile:
    path:     /cabinet/profile
    defaults: { _controller: AppBundle:Cabinet:profile }

cloud:
    path:     /cabinet/cloud
    defaults: { _controller: AppBundle:Cabinet:cloud }

history:
    path:     /cabinet/history
    defaults: { _controller: AppBundle:Cabinet:history }

content:
    path:     /cabinet/content
    defaults: { _controller: AppBundle:Cabinet:content }

news:
    path:     /cabinet/news
    defaults: { _controller: AppBundle:Cabinet:news }

faq:
    path:     /cabinet/faq
    defaults: { _controller: AppBundle:Cabinet:faq }

dashboard:
    path:     /cabinet/dashboard
    defaults: { _controller: AppBundle:Dashboard:index }

dashboard_open:
    path:     /cabinet/dashboard/open/{rate}
    defaults: { _controller: AppBundle:Dashboard:open }

dashboard_prolong:
    path:     /cabinet/dashboard/prolong
    defaults: { _controller: AppBundle:Dashboard:prolong }

accounts:
    path:     /api/accounts
    defaults: { _controller: AppBundle:API:accounts }
    methods:  [POST]