app_index:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_profile:
    path:     /cabinet/profile
    defaults: { _controller: AppBundle:Default:profile }

app_cloud:
    path:     /cabinet/cloud
    defaults: { _controller: AppBundle:Default:cloud }

app_history:
    path:     /cabinet/history
    defaults: { _controller: AppBundle:Default:history }

app_news:
    path:     /cabinet/news
    defaults: { _controller: AppBundle:Default:news }

app_support:
    path:     /cabinet/support
    defaults: { _controller: AppBundle:Default:support }

app_dashboard:
    path:     /cabinet/dashboard
    defaults: { _controller: AppBundle:Dashboard:index }

app_dashboard_payment:
    path:     /cabinet/dashboard/payment/{rate}
    defaults: { _controller: AppBundle:Dashboard:paymentTable }

app_api_post_account:
    path:     /api/account
    defaults: { _controller: AppBundle:API:postAccount }
    methods:  [POST]

app_api_post_avatar:
    path:     /api/avatar
    defaults: { _controller: AppBundle:API:postAvatar }
    methods:  [POST]

app_api_get_notifications:
    path:     /api/notifications
    defaults: { _controller: AppBundle:API:getNotifications }
    methods:  [GET]

app_api_get_notification:
    path:     /api/notification/{notification}
    defaults: { _controller: AppBundle:API:getNotification }
    methods:  [GET]

app_search_referrers:
    path:     /api/search/referrers
    defaults: { _controller: AppBundle:API:searchReferrers }
    methods:  [GET]
