services:
    app.referrer_listener:
        class: AppBundle\EventListener\ReferrerSubscriber
        arguments:
            - @doctrine.orm.default_entity_manager
        tags:
            - { name: kernel.event_subscriber }
