services:
    app.referrer_subscriber:
        class: AppBundle\EventListener\ReferrerSubscriber
        tags:
            - { name: kernel.event_subscriber }

    app.registration.form.handler:
        class: AppBundle\Form\Handler\RegistrationFormHandler
        arguments:
            - "@fos_user.registration.form"
            - "@request"
            - "@fos_user.user_manager"
            - "@fos_user.mailer"
            - "@fos_user.util.token_generator"
            - "@sonata.notification.backend"
        calls:
            - [setDefaultUsername, ["%default_username%"]]
        scope: request
        public: false

    app.form.type.registration:
        class: AppBundle\Form\Type\RegistrationType
        arguments:
            - "%fos_user.model.user.class%"
        calls:
            - [setSession, ["@session"]]
        tags:
            - { name: form.type , alias: form_user_registration }

    app.form.type.user:
        class: AppBundle\Form\Type\UserType
        arguments:
            - "@doctrine.orm.default_entity_manager"
        tags:
            - { name: form.type }

    app.form.type.pm_account:
        class: AppBundle\Form\Type\PerfectMoneyAccountType
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@logger"
        tags:
            - { name: form.type }

    app.committee_service:
        class: AppBundle\Service\Committee
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@property_accessor"

    app.cashier_service:
        class: AppBundle\Service\Cashier
        arguments:
            - "@event_dispatcher"
            - "@doctrine.orm.default_entity_manager"
            - "@app.committee_service"
            - "@app.banker_service"
            - "@property_accessor"
            - "@logger"

    app.banker_service:
        class: AppBundle\Service\Banker
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@property_accessor"
            - "@app.payment_system.perfectmoney"

    app.payment_system.perfectmoney:
        class: AppBundle\Service\PaymentSystem\PerfectMoney
        arguments:
            - "@property_accessor"
            - "@doctrine.orm.default_entity_manager"
            - "@router.default"
            - "@logger"
            - "%perfect_money%"

    app.payment_subscriber:
        class: AppBundle\EventListener\PaymentSubscriber
        arguments:
            - "@app.cashier_service"
            - "@logger"
        tags:
            - { name: kernel.event_subscriber }

    app.filter.transparent_mask:
        class: AppBundle\Imagine\Filter\Loader\TransparentMaskFilterLoader
        arguments:
            - "@liip_imagine"
            - "%kernel.root_dir%"
        tags:
            - { name: liip_imagine.filter.loader, loader: 'transparent_mask' }

    app.invoice_status.subscriber:
        class: AppBundle\EventListener\InvoiceStatusSubscriber
        tags:
            - { name: doctrine.event_subscriber }

    app.transaction_done.subscriber:
        class: AppBundle\EventListener\MoneyTransactionSubscriber
        tags:
            - { name: doctrine.event_subscriber }

    app.ticket_subscriber:
        class: AppBundle\EventListener\TicketSubscriber
        arguments:
            - "@property_accessor"
        tags:
            - { name: kernel.event_subscriber }

    app.validator.table_rules:
        class: AppBundle\Validator\Constraints\TableRulesValidator
        arguments:
            - "@property_accessor"
        tags:
            - { name: validator.constraint_validator, alias: table_rules_validator }

    app.notification.consumer:
        class: AppBundle\Notification\Consumer\NotificationConsumer
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@property_accessor"
        tags:
            - { name: sonata.notification.consumer, type: notification }