services:
    app.referrer_subscriber:
        class: AppBundle\EventListener\ReferrerSubscriber
        tags:
            - { name: kernel.event_subscriber }

    app.registration.form.handler:
        class: AppBundle\Form\Handler\RegistrationFormHandler
        arguments:
            - "@fos_user.registration.form"
            - "@request"
            - "@fos_user.user_manager"
            - "@fos_user.mailer"
            - "@fos_user.util.token_generator"
        scope: request
        public: false

    app.admin.pool:
        class: AppBundle\Admin\PoolAdmin
        arguments: [~, AppBundle\Entity\Pool, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.title.section.pool }
        calls:
            - [setEntityManager, [@doctrine.orm.default_entity_manager]]

    app.admin.rate:
        class: AppBundle\Admin\RateAdmin
        arguments: [~, AppBundle\Entity\Rate, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.title.section.rate }

    app.admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.title.section.user }
        calls:
            - [setUserManager, [@fos_user.user_manager]]
            - [setEntityManager, [@doctrine.orm.default_entity_manager]]

    app.admin.account:
        class: AppBundle\Admin\AccountAdmin
        arguments: [~, AppBundle\Entity\Account, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.title.section.account }

    app.admin.money_transaction:
        class: AppBundle\Admin\MoneyTransactionAdmin
        arguments: [~, AppBundle\Entity\MoneyTransaction, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.title.section.transaction }

    app.admin.ticket:
        class: AppBundle\Admin\TicketAdmin
        arguments: [~, AppBundle\Entity\Ticket, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.title.section.ticket }

    app.admin.invoice:
        class: AppBundle\Admin\InvoiceAdmin
        arguments: [~, AppBundle\Entity\Invoice, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.title.section.invoice }

    app.form.type.pm_account:
        class: AppBundle\Form\Type\PerfectMoneyAccountType
        arguments: [@doctrine.orm.default_entity_manager]
        tags:
            - { name: form.type }

    app.committee_service:
        class: AppBundle\Service\Committee
        arguments:
            - @doctrine.orm.default_entity_manager
            - @property_accessor

    app.cashier_service:
        class: AppBundle\Service\Cashier
        arguments:
            - @event_dispatcher
            - @doctrine.orm.default_entity_manager
            - @app.committee_service
            - @app.banker_service
            - @property_accessor

    app.banker_service:
        class: AppBundle\Service\Banker
        arguments:
            - @doctrine.orm.default_entity_manager
            - @property_accessor
            - @app.payment_system.perfectmoney

    app.payment_system.perfectmoney:
        class: AppBundle\Service\PaymentSystem\PerfectMoney
        arguments:
            - @property_accessor
            - @doctrine.orm.default_entity_manager
            - %perfect_money%
            - @logger

    app.payment_subscriber:
        class: AppBundle\EventListener\PaymentSubscriber
        arguments: [@app.cashier_service]
        tags:
            - { name: kernel.event_subscriber }

    app.filter.transparent_mask:
        class: AppBundle\Imagine\Filter\Loader\TransparentMaskFilterLoader
        arguments:
            - @liip_imagine
            - %kernel.root_dir%
        tags:
            - { name: liip_imagine.filter.loader, loader: 'transparent_mask' }
