AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [account]
            groups: [Profile]
    properties:
        firstName:
            - NotBlank:
                groups: [Profile]
        phone:
            - NotBlank:
                groups: [Profile]
        account:
            - NotBlank:
                groups: [Profile]

AppBundle\Entity\Account:
    properties:
        number:
            - Regex:
                pattern: '/^U\d+$/'
            - NotBlank: ~
            - Length:
                min: 8
                max: 8
