AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [account]
            groups: [Profile]
    properties:
        firstName:
            - NotBlank:
                groups: [Profile]
        phone:
            - NotBlank:
                groups: [Profile]
        account:
            - NotBlank:
                groups: [Profile]

AppBundle\Entity\Account:
    properties:
        number:
            - Regex:
                pattern: '/^U\d+$/'
            - NotBlank: ~
            - Length:
                min: 8
                max: 16

Symfony\Component\HttpFoundation\File\UploadedFile:
    properties:
        size:
            - GreaterThan:
                value: %upload_max_size%
        mimeType:
            - Regex: '/^image\/(?:jpeg|png)$/'

AppBundle\Entity\Rate:
    properties:
        score:
            - NotBlank: ~

AppBundle\Entity\Ticket:
    constraints:
        - AppBundle\Validator\Constraints\TableRules: ~

AppBundle\Entity\Issue:
    properties:
        subject:
            - NotBlank: ~
        body:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~
