AppBundle\Entity\Account:
    type: entity
    table: account
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        number:
            type: string
            length: 8
            unique: true
        login:
            type: string
            length: 6
            nullable: true
        merchantPassPhrase:
            type: string
            length: 32
            nullable: true
        commission:
            type: float
            nullable: true
        balance:
            type: float
            nullable: true
        system:
            type: boolean
        verified:
            type: boolean
            nullable: true
        blocked:
            type: boolean
            nullable: true
    oneToOne:
        user:
            targetEntity: AppBundle\Entity\User
            mappedBy: account
    manyToMany:
        pools:
            targetEntity: AppBundle\Entity\Pool
            mappedBy: accounts
    oneToMany:
        incomes:
            targetEntity: AppBundle\Entity\MoneyTransaction
            mappedBy: destination
        outcomes:
            targetEntity: AppBundle\Entity\MoneyTransaction
            mappedBy: source