AppBundle\Entity\Account:
    type: entity
    repositoryClass: AppBundle\Entity\AccountRepository
    table: account
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
            options:
                unsigned: true
    fields:
        number:
            type: string
            length: 10
            unique: true
            nullable: false
        login:
            type: string
            length: 8
            nullable: true
        password:
            type: string
            length: 32
            nullable: true
        passPhrase:
            type: string
            length: 32
            nullable: true
        commission:
            type: float
            nullable: true
        balance:
            type: float
            nullable: false
            precision: 2
            scale: 2
        profit:
            type: float
            nullable: false
            precision: 2
            scale: 2
        system:
            type: boolean
            nullable: false
        verified:
            type: boolean
            nullable: true
        blocked:
            type: boolean
            nullable: false
    oneToOne:
        user:
            targetEntity: AppBundle\Entity\User
            mappedBy: account
    manyToMany:
        pools:
            targetEntity: AppBundle\Entity\Pool
            mappedBy: accounts
    oneToMany:
        incomes:
            targetEntity: AppBundle\Entity\MoneyTransaction
            mappedBy: destination
        outcomes:
            targetEntity: AppBundle\Entity\MoneyTransaction
            mappedBy: source