AppBundle\Entity\Invoice:
    type: entity
    repositoryClass: AppBundle\Entity\InvoiceRepository
    table: invoice
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
            options:
                unsigned: true
    fields:
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
        expiredAt:
            type: datetime
            nullable: false
        amount:
            type: float
            precision: 2
            scale: 2
            nullable: false
        paid:
            type: float
            precision: 2
            scale: 2
            nullable: false
        period:
            type: integer
            nullable: false
            options:
                unsigned: true
        status:
            type: smallint
            nullable: false
            options:
                unsigned: true
    oneToMany:
        transactions:
            targetEntity: AppBundle\Entity\MoneyTransaction
            mappedBy: invoice
    manyToOne:
        ticket:
            targetEntity: AppBundle\Entity\Ticket
            inversedBy: invoices
            joinColumn:
                name: ticket_id
                referencedColumnName: id
                nullable: true
                options:
                    unsigned: true
        user:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: false
                options:
                    unsigned: true
        rate:
            targetEntity: AppBundle\Entity\Rate
            joinColumn:
                name: rate_id
                referencedColumnName: id
                nullable: false
                options:
                    unsigned: true
    lifecycleCallbacks:
        prePersist: [onCreate]
        preUpdate: [onUpdate]
