AppBundle\Entity\Invoice:
    type: entity
    table: invoice
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
        expiredAt:
            type: datetime
        amount:
            type: float
        paid:
            type: float
        period:
            type: integer
        status:
            type: smallint
    oneToMany:
        transactions:
            targetEntity: AppBundle\Entity\MoneyTransaction
            mappedBy: invoice
    manyToOne:
        ticket:
            targetEntity: AppBundle\Entity\Ticket
            inversedBy: invoices
            joinColumn:
                name: ticket_id
                referencedColumnName: id
                nullable: false #todo убрать когда нужны будут выставление внутренних счетов
    lifecycleCallbacks:
        prePersist: [onCreate]
        preUpdate: [onUpdate]
