AppBundle\Entity\MoneyTransaction:
    type: entity
    repositoryClass: AppBundle\Entity\MoneyTransactionRepository
    table: money_transaction
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
            options:
                unsigned: true
    fields:
        amount:
            type: float
            precision: 2
            scale: 2
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
        status:
            type: smallint
            options:
                unsigned: true
        note:
            type: string
            nullable: true
        type:
            type: smallint
            options:
                unsigned: true
        external:
            type: integer
            nullable: true
            options:
                unsigned: true
        attempts:
            type: smallint
            nullable: false
            options:
                unsigned: true
    manyToOne:
        source:
            targetEntity: AppBundle\Entity\Account
            inversedBy: outcomes
            joinColumn:
                name: source_id
                referencedColumnName: id
                nullable: false
                options:
                    unsigned: true
        destination:
            targetEntity: AppBundle\Entity\Account
            inversedBy: incomes
            joinColumn:
                name: destination_id
                referencedColumnName: id
                nullable: false
                options:
                    unsigned: true
        invoice:
            targetEntity: AppBundle\Entity\Invoice
            inversedBy: transactions
            joinColumn:
                name: invoice_id
                referencedColumnName: id
                options:
                    unsigned: true
    lifecycleCallbacks:
        prePersist: [onCreate]
        preUpdate: [onUpdate]