AppBundle\Entity\MoneyTransaction:
    type: entity
    table: money_transaction
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        amount:
            type: float
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
        status:
            type: smallint
        note:
            type: string
            nullable: true
        type:
            type: smallint
        external:
            type: string
            length: 50
            nullable: true
    manyToOne:
        source:
            targetEntity: AppBundle\Entity\Account
            inversedBy: outcomes
            joinColumn:
                name: source_id
                referencedColumnName: id
                nullable: false
        destination:
            targetEntity: AppBundle\Entity\Account
            inversedBy: incomes
            joinColumn:
                name: destination_id
                referencedColumnName: id
                nullable: false
        invoice:
            targetEntity: AppBundle\Entity\Invoice
            inversedBy: transactions
            joinColumn:
                name: invoice_id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [onCreate]
        preUpdate: [onUpdate]