AppBundle\Entity\Pool:
    type: entity
    table: pool
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
            options:
                unsigned: true
    fields:
        name:
            type: string
            length: 15
            nullable: true
    manyToMany:
        accounts:
            targetEntity: AppBundle\Entity\Account
            inversedBy: pools
            joinTable:
                name: pool_account
                joinColumns:
                    pool_id:
                        referencedColumnName: id
                        nullable: false
                        options:
                            unsigned: true
                inverseJoinColumns:
                    account_id:
                        referencedColumnName: id
                        nullable: false
                        options:
                            unsigned: true