AppBundle\Entity\Qualification:
    type: entity
    table: qualification
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
            options:
                unsigned: true
    fields:
        passed:
            type: boolean
            nullable: false
        requireInvitation:
            type: smallint
            nullable: true
            options:
                unsigned: true
    oneToOne:
        ticket:
            targetEntity: AppBundle\Entity\Ticket
            inversedBy: qualification
            joinColumn:
                name: ticket_id
                referencedColumnName: id
                nullable: flase
                options:
                    unsigned: true
    manyToMany:
        transferredTickets:
            targetEntity: AppBundle\Entity\Ticket
            joinTable:
                name: qualifications_tickets
                joinColumns:
                    qualification_id:
                        referencedColumnName: id
                        options:
                            unsigned: true
                inverseJoinColumns:
                    ticket_id:
                        referencedColumnName: id
                        options:
                            unsigned: true