AppBundle\Entity\Rate:
    type: entity
    repositoryClass: AppBundle\Entity\RateRepository
    table: rate
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
            options:
                unsigned: true
    fields:
        name:
            type: string
            length: 100
            nullable: true
        amount:
            type: float
            precision: 2
            scale: 2
            nullable: false
        commission:
            type: float
            precision: 1
            scale: 1
            nullable: false
        period:
            type: smallint
            nullable: false
            options:
                unsigned: true
        members:
            type: integer
            nullable: false
            options:
                unsigned: true
        requireQualification:
            type: boolean
            nullable: false
        requireInvitation:
            type: integer
            nullable: true
            options:
                unsigned: true
    manyToOne:
        pool:
            targetEntity: AppBundle\Entity\Pool
            joinColumn:
                name: pool_id
                referencedColumnName: id
                nullable: false
                options:
                    unsigned: true
    oneToMany:
        tickets:
            targetEntity: AppBundle\Entity\Ticket
            mappedBy: rate
    uniqueConstraints:
        unique_rate:
            columns: [amount, commission, period, require_qualification, require_invitation]