AppBundle\Entity\Rate:
    type: entity
    table: rate
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 100
            nullable: true
        amount:
            type: float
            precision: 2
            scale: 2
        commission:
            type: float
            precision: 1
            scale: 1
        period:
            type: smallint
        members:
            type: integer
        requireQualification:
            type: boolean
        requireInvitation:
            type: integer
    manyToOne:
        pool:
            targetEntity: AppBundle\Entity\Pool
            joinColumn:
                name: pool_id
                referencedColumnName: id
                nullable: false
    oneToMany:
        tickets:
            targetEntity: AppBundle\Entity\Ticket
            mappedBy: rate
    uniqueConstraints:
        unique_rate:
            columns: [amount, commission, period, require_qualification, require_invitation]