AppBundle\Entity\Ticket:
    type: entity
    repositoryClass: AppBundle\Entity\TicketRepository
    table: ticket
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        paidUp:
            type: datetime
            nullable: true
        paid:
            type: boolean
        type:
            type: integer
        expired:
            type: boolean
    oneToOne:
        qualification:
            targetEntity: AppBundle\Entity\Qualification
            mappedBy: ticket
    manyToOne:
        user:
            targetEntity: AppBundle\Entity\User
            inversedBy: tickets
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: false
        rate:
            targetEntity: AppBundle\Entity\Rate
            inversedBy: tickets
            joinColumn:
                name: rate_id
                referencedColumnName: id
                nullable: false
        chiefTicket:
            targetEntity: AppBundle\Entity\Ticket
            inversedBy: subordinates
            joinColumn:
                name: chief_ticket_id
                referencedColumnName: id
    oneToMany:
        invoices:
            targetEntity: AppBundle\Entity\Invoice
            mappedBy: ticket
        subordinates:
            targetEntity: AppBundle\Entity\Ticket
            mappedBy: chiefTicket
    uniqueConstraints:
        unique_ticket:
            columns: [user_id, rate_id]