AppBundle\Entity\Ticket:
    type: entity
    table: ticket
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        paidUp:
            type: datetime
            nullable: true
        paid:
            type: boolean
        subscribed:
            type: boolean
    manyToOne:
        user:
            targetEntity: AppBundle\Entity\User
            inversedBy: tickets
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: false
        rate:
            targetEntity: AppBundle\Entity\Rate
            inversedBy: tickets
            joinColumn:
                name: rate_id
                referencedColumnName: id
                nullable: false
    oneToOne:
        chiefTicket:
            targetEntity: AppBundle\Entity\Ticket
            joinColumn:
                name: chief_ticket_id
                referencedColumnName: id
    oneToMany:
        invoices:
            targetEntity: AppBundle\Entity\Invoice
            mappedBy: ticket


