AppBundle\Entity\User:
    type: entity
    repositoryClass: AppBundle\Entity\UserRepository
    table: user
    gedmo:
        tree:
            type: 'materializedPath'
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
            gedmo: [treePathSource]
            options:
                unsigned: true
    fields:
        firstName:
            type: string
            length: 15
            nullable: true
        middleName:
            type: string
            length: 15
            nullable: true
        lastName:
            type: string
            length: 15
            nullable: true
        phone:
            type: string
            nullable: true
            length: 13
        avatar:
            type: string
            nullable: true
        vkontakte:
            type: string
            nullable: true
        path:
            type: string
            nullable: true
            length: 1024
            gedmo:
                treePath:
                    separator: ':'
                    endsWithSeparator: false
        level:
            type: integer
            nullable: true
            gedmo: [treeLevel]
            options:
                unsigned: true
    oneToOne:
        account:
            targetEntity: AppBundle\Entity\Account
            inversedBy: user
            joinColumn:
                name: account_id
                referencedColumnName: id
                options:
                    unsigned: true
    oneToMany:
        tickets:
            targetEntity: AppBundle\Entity\Ticket
            mappedBy: user
        referrals:
            targetEntity: AppBundle\Entity\User
            mappedBy: referrer
    manyToOne:
        referrer:
            gedmo: [treeParent]
            targetEntity: AppBundle\Entity\User
            inversedBy: referrals
            joinColumn:
                name: referrer_id
                referencedColumnName: id
                options:
                    unsigned: true