AppBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 15
            nullable: true
        middleName:
            type: string
            length: 15
            nullable: true
        lastName:
            type: string
            length: 15
            nullable: true
        phone:
            type: string
            nullable: true
            length: 13
        avatar:
            type: string
            nullable: true
        vkontakte:
            type: string
            nullable: true
    oneToOne:
        account:
            targetEntity: AppBundle\Entity\Account
            inversedBy: user
            cascade: [persist]
            joinColumn:
                name: account_id
                referencedColumnName: id
    oneToMany:
        tickets:
            targetEntity: AppBundle\Entity\Ticket
            mappedBy: user
    manyToOne:
        referrer:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: referrer_id
                referencedColumnName: id